version: '3'

services:
  db:
    env_file: .env
    container_name: db
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  api:
    env_file: .env
    container_name: api
    image: monal
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "80:8080"


volumes:
  db:
    driver: local
