name: backend tests and checkstyle
run-name: Checking backend by @${{ github.actor }}

on: [ push, pull_request ]

permissions:
  id-token: write
  contents: read
  checks: write

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: adopt
          cache: 'maven'

      - name: Build
        run: mvn package -B -DskipTests -Dskip.installyarn -Dskip.yarn -Dcheckstyle.skip
        env:
          CI: ""

      - name: Test
        run: mvn surefire:test -B -Dmaven.test.failure.ignore=true -Djacoco.destFile=exportJacoco/jacoco-unit.exec

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Unit tests report
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true

      - name: Coverage Report
        uses: actions/upload-artifact@v2
        with:
          name: unit-tests-jacoco
          path: exportJacoco/jacoco-unit.exec


  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: adopt
          cache: 'maven'

#      - name: Build
#        run: mvn package -B -DskipTests -Dskip.installyarn -Dskip.yarn -Dcheckstyle.skip
#        env:
#          CI: ""

      - name: Test
        run: mvn verify 
            -B
            -Dskip.installyarn
            -Dskip.yarn
            -Dcheckstyle.skip
            -Dspring.profiles.active=test
            -Dmaven.test.failure.ignore=true
            -Djacoco.destFile=exportJacoco/jacoco-it.exec

      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Integration tests report
          path: target/failsafe-reports/TEST-*.xml
          reporter: java-junit
          fail-on-error: true

      - name: Coverage Report
        uses: actions/upload-artifact@v2
        with:
          name: integration-tests-jacoco
          path: exportJacoco/jacoco-it.exec


  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: adopt
          cache: 'maven'

      - name: Build and checkstyle
        run: mvn verify -B -DskipTests -Dskip.installyarn -Dskip.yarn checkstyle:checkstyle

      - name: Report
        uses: jwgmeligmeyling/checkstyle-github-action@master
        with:
          name: Checkstyle report
          path: '**/checkstyle-result.xml'
