name: backend-tests
run-name: Testing backend by @${{ github.actor }}

on: [ push, pull_request ]

permissions:
  id-token: write
  contents: read
  checks: write

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: adopt
          cache: 'maven'

      - name: Build
        run: mvn package --batch-mode -DskipTests -Dcheckstyle.skip
        env:
          CI: ""

      - name: Test
        run: mvn surefire:test --batch-mode -Dmaven.test.failure.ignore=true

      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Unit tests report
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true

  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: adopt
          cache: 'maven'

      - name: Build
        run: mvn package --batch-mode -DskipTests -Dcheckstyle.skip
        env:
          CI: ""

      - name: Test
        run: mvn failsafe:integration-test --batch-mode -Dmaven.test.failure.ignore=true

      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Integration tests report
          path: target/failsafe-reports/TEST-*.xml
          reporter: java-junit
          fail-on-error: true
