name: frontend test and lint
run-name: Checking frontend by @${{ github.actor }}

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  id-token: write
  contents: read
  checks: write

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/main/frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
          cache-dependency-path: src/main/frontend

      - name: Install dependencies
        run: yarn

      - name: Run tests
        run: yarn test --coverage

      - name: test current location
        run: cd coverage && ls -la

      - name: Jest Coverage Comment
        uses: MishaKav/jest-coverage-comment@main
        with:
          coverage-summary-path: ./coverage/coverage-final.json

  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/main/frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
          cache-dependency-path: src/main/frontend

      - name: Install dependencies
        run: yarn

      - name: Run ESLint
        run: yarn eslint

      - name: Run Stylelint
        run: yarn stylelint
