name: Java checkstyle

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: adopt
          cache: 'maven'

      - name: Build and checkstyle
        run: mvn verify -B -DskipTests -Dskip.installyarn -Dskip.yarn checkstyle:checkstyle

      - name: Report
        uses: jwgmeligmeyling/checkstyle-github-action@master
        with:
          path: '**/checkstyle-result.xml'
