name: backend-tests
run-name: Testing backend by @${{ github.actor }}

on: [ push, pull_request ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: adopt

      - name: Build
        run: mvn package --batch-mode -DskipTests
        env:
          CI: ""

      - name: Test
        run: mvn surefire:test --batch-mode -Dmaven.test.failure.ignore=true

      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Unit tests report
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true
